name: Second action

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['First action']
    types: [completed]

jobs:
  second:
    runs-on: windows-latest
    steps:
      - run: echo "Second action successfully finished!"

      - name: Download Bicep Artifacts
        uses: actions/download-artifact@v4
        with:
          name: bicep-artifacts
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show downloaded artifacts
        run: |
          dir

      - name: Read Bicep File Name and Directory
        run: |
            echo "BICEP_FILE_NAME=$(cat bicepFileName.txt)" >> $env:GITHUB_ENV
            echo "BICEP_DIRECTORY=$(cat bicepDirectory.txt)" >> $env:GITHUB_ENV

      - name: Determine specific Documentation Directory location
        run: |
              echo "bicep directory is.. ${{ env.BICEP_DIRECTORY }}"
              echo "bicep file name is.. ${{ env.BICEP_FILE_NAME }}"
              # Extract the ./doc/Bicep/ directory name (eg: atomic, composite, service, type) from the $BICEP_DIRECTORY variable

              if ( "${{ env.BICEP_DIRECTORY }}" -match "src/main/bicep/(.*)") {
                $DOC_FOLDER = $matches[1]
                echo "DOC_FOLDER=$DOC_FOLDER"  >> $env:GITHUB_ENV
                echo "DOC_FOLDER is ${{ env.DOC_FOLDER }} or $DOC_FOLDER oror env.DOC_FOLDER"
              } else {
                Write-Error "Failed to determine doc output folder"
                exit 1
              }